### ISSUE TITLE
Stopwatch timing inaccurate on various machines

### ISSUE THREAD

**Issue by FultonLX** [bitfocus/companion-module-generic-stopwatch#1]
We've noticed the stopwatch time to be slow/inaccurate on most of our installs of 3.2.2+6688-stable-7417d2a0

How slow/innaccurate isn't consistent between machines.

To test, I'm starting and stopping the stopwatch with a 120000ms delay, so I expect 2m0s0ms on the stopwatch. The 120000ms delay is accurate, measured with a realtime clock and external stopwatch. 

Desktop Windows 11 Pro / Intel Pentium Silver N6005: **1m35s600ms**
Desktop Windows 11 Pro / Intel Atom N100: **1m36s150ms**
Desktop macOS Ventura 13.6.5 / M1 Max: **1m57s450ms**
Laptop Windows 11 Pro / Intel Core i7 1255U: **1m58s800ms**
Desktop Windows 11 Pro / AMD Ryzen 7940HS: **1m59s150ms**
Desktop Windows 11 Pro / Intel Core i7 13900k: **1m59s500ms**

Seems to depend on processors.

**Comment by josephdadams** [comment]
I just pushed `v1.0.3` of the module with some performance improvements.
