### ISSUE TITLE
Stopwatch Precision

### ISSUE THREAD

**Issue by jfleckc** [bitfocus/companion-module-generic-stopwatch#12]
The stopwatch only seems to increment in 0.5sec (500ms) jumps. For example, the time in seconds and milliseconds will progress from 0.0 -> 0.501 -> 1.002 -> 1.503 -> 2.004 -> 2.505, etc.

Is there any way the precision could be improved with smaller increments?

OS: MacOS 14.5, Companion version: v3.4.0+7243-main-ea99035a

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-generic-stopwatch/blob/fb81b59728586f939f84d1a8dacf94d51a9457a1/index.js#L28

Defined here. Maybe it could be added to the module config with a default of 500.

**Comment by josephdadams** [comment]
added in `v1.1.0` of the module

**Comment by jfleckc** [comment]
Just tested, works great, thanks @josephdadams !
