### ISSUE TITLE
Incorrect rounding of seconds in "hmsms" and "seconds"

### ISSUE THREAD

**Issue by astellingwerf** [bitfocus/companion-module-generic-stopwatch#5]
If I start a countdown timer, let it run for less than a second and stop it, the time displayed from the "hmsms" variable values showing a value higher than the start value. For example, a stopwatch of just 5 seconds, after a short downward run shows "0:00:05.499". This is because the seconds value is rounded up instead of down, like the hours and minutes are.

This bug was introduced as part of 939c994, but I somehow highly doubt that it's really a performance improvement.

**Comment by josephdadams** [comment]
That hurt my feelings.

**Comment by astellingwerf** [comment]
Is it something I said?
