### ISSUE TITLE
Custom feature

### ISSUE THREAD

**Issue by DougieDK** [bitfocus/companion-module-generic-stopwatch#6]
Would it somehow be possible to only count seconds+minutes?

This is for use in a diving scenario where companion is used as a logbook. Everything is logged in seconds and minutes.

Three digit minuts is needed. I.e. 244 minutes 22 seconds.

**Comment by astellingwerf** [comment]
That makes sense on multiple levels, like for low numbers of minutes, there may be a use case to not roll them into the minutes field, but show as e.g. 164 seconds.

**Comment by pandahej** [comment]
I really second this. Having a limit of only 60 seconds or using minutes are very limiting.

**Comment by josephdadams** [comment]
added in `v1.1.0` of the module
